insert into roles(name) VALUES ('Value1');
insert into roles(name) VALUES ('Value2');
insert into roles(name) VALUES ('Value3');
insert into rules(name) VALUES ('Open');
insert into users(name, roles_id) VALUES ('Ivan', 2);
insert into users(name, roles_id) VALUES ('Ivan', 3);
insert into stateItem(name) VALUES ('Value1');
insert into stateItem(name) VALUES ('Value2');
insert into category(name) VALUES ('Value1');
insert into category(name) VALUES ('Value2');
insert into item(name, users_id, category_id, stateItem_id) VALUES ('Огурец', 1, 2, 2);
insert into item(name, users_id, category_id, stateItem_id) VALUES ('Огурец', 2, 1, 1);
insert into comments_file(name, item_id) VALUES ('XxX', 1);
insert into attachs(name, item_id) VALUES ('XxX', 2);
insert into roles_rules(roles_id, rules_id) VALUES (1, 1);